### ISSUE TITLE
M2.4.1 Class Diagram

### ISSUE THREAD

**Issue by youfu123** [Jasmin-Yap/ICT2x01-p4-1#48]
22 Oct 
You Fu
- Created Class Diagram

27 Oct
You Fu
- Added Scoreboard Data
- Updated various classes

28 Oct
You Fu
- Synced with Sequence Diagram

03 Nov
You Fu
- Added new getter and setter for sensor data and statistical data entity

**Comment by irfanzulfa** [comment]
04 Nov
Arief
- Updated on boundary classes 
- Sorted on the entities
- Added the associations
